"""update form-data table

Revision ID: 75bd5d5fc168
Revises: 2996796d3807
Create Date: 2025-08-21 13:58:06.739051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bd5d5fc168'
down_revision: Union[str, None] = '2996796d3807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('apartment_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_data', 'apartment_number')
    # ### end Alembic commands ###
