"""update report tables clean

Revision ID: ae81c3a80d8e
Revises: bda5de5dc878
Create Date: 2025-07-31 15:09:24.307907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae81c3a80d8e'
down_revision: Union[str, None] = 'bda5de5dc878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('residence_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'reports', 'residences', ['residence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'residence_id')
    # ### end Alembic commands ###
