"""update guard and owner tables

Revision ID: f488ec09d5e2
Revises: 35d424c35222
Create Date: 2025-06-27 12:46:04.744004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f488ec09d5e2'
down_revision: Union[str, None] = '35d424c35222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guards', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('owners', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'email')
    op.drop_column('guards', 'email')
    # ### end Alembic commands ###
